### ISSUE TITLE
where db ?

### ISSUE THREAD

**Issue by andrinda** [rafacla/budget-app#15]
hii guys i want try this apps where you save db ?:D

**Comment by rafacla** [comment]
hi there, i'm uploading the structure dump for you testing.
I'm going to say sorry in advance because a good part of this Project is written in portuguese, I never thought anyone else would be interested, and I'm glad you did hehe.

I hope you can find yourself by now, you are going to need to change database configs at /application/config/database.php

If you want to take a ride first, you can check it working in budget.mimv.info

There are a few bugs yet, but I'm using it already for my personal use.

Cheers,
Rafael
